[tool.poetry]
name = "mycrypto-2"
version = "0.1.0"
description = ""
authors = ["WillBell1 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
sympy = "^1.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
